<!DOCTYPE html>
<html lang="en">
<head>
    <title>Variables Default</title>
</head>
<body>
    <h1>Default Of Variables</h1>
    <?php
    /*Default of variables
     boolean value = False;
     integers = 0;
     float = 0;
     strings = "";
     arrays = [];
     objects = null;
     

    */
    $name = "Wycliff Kimani";
    $age = 22;
    ?>

    <p>My name is <?php echo $name;?> . I am <?php echo $age;?> Years old, And I am learning PHP programming  </p>
</body>
</html>