

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PHP notes</title>
</head>
<body>
    <?php
    echo "<h1>PHP NOTES </h1>";
    $number1 = 234567890985747478;
    var_dump ($number1);
    $number2 = 22.213;
    var_dump($number2);
    #//var_dump is used to know the type of the variable
    $booll = true;
    var_dump($booll);
    $names = array("Kim","Jack","Douglas","MAryanne","Wycliff","Johnson","Michael",) ;
    var_dump($names) // used to output the type of valuable 
    // suoergoblas 
    /*$GLOBALS
      $_SERVER
      $_REQUEST
      $_POST
      $_GET
      $_FILES
      $_ENV
      $_COOKIE
      $_SESSION 
    */
    ?>
</body>
</html>